service: ai-videos-manager

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  profile: steven
  environment:
    DB_CONN_STRING: ${ssm:/aivideosmanager/${self:provider.stage}/db_conn_string}

# Package configuration to include mongodb
package:
  patterns:
    - '!node_modules/.bin/**'
    - 'node_modules/**'
    - 'src/**'
    - 'package.json'
    - 'package-lock.json'

functions:
  createProject:
    handler: src/handlers/create_project.handler
    events:
      - http:
          path: /create-project
          method: post
          cors: true
          # Using Lambda Proxy integration instead of Lambda integration
          # This will pass through the status code from your Lambda response