service: ai-videos-manager

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  profile: steven
  environment:
    DB_CONN_STRING: ${ssm:/aivideosmanager/${self:provider.stage}/db_conn_string}

functions:
  createProject:
    handler: src/handlers/create_project.handler
    events:
      - http:
          path: /create-project
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowCredentials: true