service: ai-videos-manager

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  profile: steven
  environment:
    DB_CONN_STRING: ${ssm:/aivideosmanager/${self:provider.stage}/db_conn_string}

# Package configuration to include mongodb
package:
  patterns:
    - '!node_modules/.bin/**'
    - 'node_modules/**'
    - 'src/**'
    - 'package.json'
    - 'package-lock.json'

functions:
  createProject:
    handler: src/handlers/create_project.handler
    events:
      - http:
          path: /project
          method: post
          cors: true
  getProjects:
    handler: src/handlers/get_projects.handler
    events:
      - http:
          path: /project
          method: get
          cors: true
  deleteProject:
    handler: src/handlers/delete_project.handler
    events:
      - http:
          path: /project/{id}
          method: delete
          cors: true
  updateProject:
    handler: src/handlers/update_project.handler
    events:
      - http:
          path: /project/{id}
          method: put
          cors: true