service: ai-videos-manager

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  profile: steven
  environment:
    DB_CONN_STRING: ${ssm:/aivideosmanager/${self:provider.stage}/db_conn_string}
    ELEVENLABS_API_KEY: ${ssm:/aivideosmanager/${self:provider.stage}/elevenlabs_api_key}
    LEONARDO_API_KEY: ${ssm:/aivideosmanager/${self:provider.stage}/leonardo_api_key}
    LEONARDO_API_URL: https://cloud.leonardo.ai/api/rest/v1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
            - s3:PutObjectAcl
          Resource:
            - arn:aws:s3:::steven-aivideos
            - arn:aws:s3:::steven-aivideos/*

# Package configuration to include mongodb
package:
  patterns:
    - '!node_modules/.bin/**'
    - 'node_modules/**'
    - 'src/**'
    - 'package.json'
    - 'package-lock.json'

resources:
  Resources:
    AudioBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: steven-aivideos
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - '*'

functions:
  createProject:
    handler: src/handlers/create_project.handler
    events:
      - http:
          path: /project
          method: post
          cors: true
  getProject:
    handler: src/handlers/get_project.handler
    events:
      - http:
          path: /project/{id}
          method: get
          cors: true
  getProjects:
    handler: src/handlers/get_projects.handler
    events:
      - http:
          path: /project
          method: get
          cors: true
  deleteProject:
    handler: src/handlers/delete_project.handler
    events:
      - http:
          path: /project/{id}
          method: delete
          cors: true
  updateProject:
    handler: src/handlers/update_project.handler
    events:
      - http:
          path: /project/{id}
          method: put
          cors: true
  createAudio:
    handler: src/handlers/create_audio.handler
    timeout: 28
    events:
      - http:
          path: /project/{id}/audio
          method: post
          cors: true
  createImages:
    handler: src/handlers/create_images.handler
    events:
      - http:
          path: /project/{id}/images
          method: post
          cors: true
  leonardoWebhook:
    handler: src/handlers/leonardo_webhook.handler
    events:
      - http:
          path: /leonardo/webhook
          method: post
          cors: true
  downloadProject:
    handler: src/handlers/download_project.handler
    timeout: 30
    events:
      - http:
          path: /project/{id}/download
          method: get
          cors: true